# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm2mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineDatafile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDatafile.setObjectName("lineDatafile")
        self.horizontalLayout.addWidget(self.lineDatafile)
        self.pushDatafile = QtWidgets.QPushButton(self.centralwidget)
        self.pushDatafile.setObjectName("pushDatafile")
        self.horizontalLayout.addWidget(self.pushDatafile)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineChooseFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineChooseFolder.setObjectName("lineChooseFolder")
        self.horizontalLayout_2.addWidget(self.lineChooseFolder)
        self.pushChooseFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushChooseFolder.setObjectName("pushChooseFolder")
        self.horizontalLayout_2.addWidget(self.pushChooseFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textConsole = QtWidgets.QTextEdit(self.centralwidget)
        self.textConsole.setObjectName("textConsole")
        self.horizontalLayout_3.addWidget(self.textConsole)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.push1 = QtWidgets.QPushButton(self.centralwidget)
        self.push1.setMinimumSize(QtCore.QSize(50, 50))
        self.push1.setObjectName("push1")
        self.verticalLayout.addWidget(self.push1)
        self.push2 = QtWidgets.QPushButton(self.centralwidget)
        self.push2.setMinimumSize(QtCore.QSize(50, 50))
        self.push2.setObjectName("push2")
        self.verticalLayout.addWidget(self.push2)
        self.push3 = QtWidgets.QPushButton(self.centralwidget)
        self.push3.setMinimumSize(QtCore.QSize(50, 50))
        self.push3.setObjectName("push3")
        self.verticalLayout.addWidget(self.push3)
        self.push4 = QtWidgets.QPushButton(self.centralwidget)
        self.push4.setMinimumSize(QtCore.QSize(50, 50))
        self.push4.setObjectName("push4")
        self.verticalLayout.addWidget(self.push4)
        self.push5 = QtWidgets.QPushButton(self.centralwidget)
        self.push5.setMinimumSize(QtCore.QSize(50, 50))
        self.push5.setObjectName("push5")
        self.verticalLayout.addWidget(self.push5)
        self.push6 = QtWidgets.QPushButton(self.centralwidget)
        self.push6.setMinimumSize(QtCore.QSize(50, 50))
        self.push6.setObjectName("push6")
        self.verticalLayout.addWidget(self.push6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushDatafile.setText(_translate("MainWindow", "OPEN DATAFILE"))
        self.pushChooseFolder.setText(_translate("MainWindow", "OPEN DEST FOLDER"))
        self.push1.setText(_translate("MainWindow", "1"))
        self.push2.setText(_translate("MainWindow", "2"))
        self.push3.setText(_translate("MainWindow", "3"))
        self.push4.setText(_translate("MainWindow", "4"))
        self.push5.setText(_translate("MainWindow", "5"))
        self.push6.setText(_translate("MainWindow", "6"))

